AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role Create

Parameters: 
# ------------------------------------------------------------#
#  NameBase
# ------------------------------------------------------------#
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10

Resources: 
# ------------------------------------------------------------#
#  IAMRole
# ------------------------------------------------------------#
  #IAMRole
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com
      Path: "/"
      ManagedPolicyArns:                    
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  #AccessPolicies
  AccessPolicies:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Sub "${NameBase}-access"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - "s3:ListBucket"
          Resource: 
            - !Sub "arn:aws:s3:::${NameBase}"
        - Effect: Allow
          Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:DeleteObject"
          Resource: !Sub "arn:aws:s3:::${NameBase}/*"
      Roles:
      - !Ref IAMRole
  #InstanceProfile
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref IAMRole
Outputs:
# InstanceProfile:
  InstanceProfile:
    Value: !Ref InstanceProfile
    Export:
      Name: InstanceProfile