AWSTemplateFormatVersion: 2010-09-09
Description: VPC and Subnet Create

Parameters:
# ------------------------------------------------------------#
#  NameBase
# ------------------------------------------------------------#
  NameBase:
    Description: this is base name.
    Type: String
    Default: lecture10

Resources: 
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
  VPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/21
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-vpc"

# InternetGateway Create
  InternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-igw"

# IGW Attach
  InternetGatewayAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC 

# ------------------------------------------------------------#
#  Subnet
# ------------------------------------------------------------#  
# Public Subnet1a Create
  PublicSubnet1a: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-public-subnet-1a"

# Public Subnet1c Create
  PublicSubnet1c: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-public-subnet-1c"

# Private Subnet1a Create
  PrivateSubnet1a: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.3.0/24
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-private-subnet-1a"

# Private Subnet1c Create
  PrivateSubnet1c: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.4.0/24
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-private-subnet-1c"
# ------------------------------------------------------------#
#  RouteTable
# ------------------------------------------------------------#          
# Public RouteTable Create
  PublicRouteTable: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-public-route"

# Private RouteTable1a Create
  PrivateRouteTable1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-private-route-1a"

# Private RouteTableC Create
  PrivateRouteTable1c: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${NameBase}-private-route-1c"
# ------------------------------------------------------------#
# Routing
# ------------------------------------------------------------# 
# PublicRouteA Create
  PublicRoute: 
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId: !Ref PublicRouteTable 
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
# ------------------------------------------------------------#
# RouteTable Associate
# ------------------------------------------------------------# 
# PublicRouteTable Associate Subnet1a
  PublicSubnetRouteTableAssociation1a: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref PublicSubnet1a
      RouteTableId: !Ref PublicRouteTable

# PublicRouteTable Associate Subnet1c
  PublicSubnetRouteTableAssociation1c: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PublicSubnet1c
      RouteTableId: !Ref PublicRouteTable

# PrivateRouteTable Associate Subnet1a
  PrivateSubnetRouteTableAssociation1a: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref PrivateSubnet1a
      RouteTableId: !Ref PrivateRouteTable1a

# PrivateRouteTable Associate Subnet1c
  PrivateSubnetCRouteTableAssociation1c: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      SubnetId: !Ref PrivateSubnet1c
      RouteTableId: !Ref PrivateRouteTable1c
# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------# 
Outputs:
# VPC
  VPC:
    Value: !Ref VPC
    Export:
      Name: VPC
# Subnet
  PublicSubnet1a:
    Value: !Ref PublicSubnet1a
    Export:
      Name: PublicSubnet1a

  PublicSubnet1c:
    Value: !Ref PublicSubnet1c
    Export:
      Name: PublicSubnet1c

  PrivateSubnet1a:
    Value: !Ref PrivateSubnet1a
    Export:
      Name: PrivateSubnet1a

  PrivateSubnet1c:
    Value: !Ref PrivateSubnet1c
    Export:
      Name: PrivateSubnet1c